# T5転移学習 - ベースライン（10エポック版）
# 比較実験用：T5を使わない設定、Early Stopping付き

# 共通設定を継承
extends: shared_base.yaml

# transfer_learning を明示的に無効化
transfer_learning:
  use_pretrained_lm: false

# 10エポック設定のオーバーライド
training:
  epochs: 5                       # 統一設定：5エポック
  early_stop:
    patience: 3                   # 3エポック改善なしで早期終了
    min_delta: 0.001

# 実行設定
runtime:
  experiment_name: "baseline_no_t5_10ep"