# T5転移学習 - ベースライン（10エポック版）
# 比較実験用：T5を使わない設定、Early Stopping付き

# 共通設定を継承
extends: shared_base.yaml

# transfer_learning を明示的に無効化
transfer_learning:
  use_pretrained_lm: false

# データ設定は shared_base.yaml から継承

# モデルアーキテクチャ（共通設定を一部オーバーライド）
model:
  tf_stem:
    kernel_size: 3
    d_model: 64
    
  encoder:
    n_layers: 4
    d_model: 64
    d_state: 8
    d_conv: 4
    expand: 2
    cross_attn_every: 2
    flash_attn: true
    
  bottleneck:
    latent_len: 16              # seq_len/8 = 128/8 = 16
    stride: 8
    
  decoder:
    n_layers: 2
    kernel_size: 3
    
  positional:
    intra_tf: "rotary"
    inter_tf: "learned"

# 訓練設定（10エポック版）
training:
  epochs: 5                       # 統一設定：5エポック
  early_stop:
    patience: 3                   # 3エポック改善なしで早期終了
    min_delta: 0.001
    
  precision: "16-mixed"

# その他の設定は shared_base.yaml から継承

# 実行設定
runtime:
  experiment_name: "baseline_no_t5_10ep"