# T5転移学習 - 1%データ版（高速テスト用）
# データ量を1/100に削減してテスト実行

# 共通設定を継承
extends: t5_large_nofreeze.yaml

# 開発用設定（1%データ）
development:
  limit_train_batches: 31    # 3122の約1% (3122 * 0.01 = 31.22)
  limit_val_batches: 6       # 606の約1% (606 * 0.01 = 6.06)
  
# バッチサイズも調整（メモリ節約）
training:
  batch_size: 256           # 768 → 256に削減
  epochs: 3                 # エポック数も削減してテスト

# 実行設定
runtime:
  experiment_name: "t5_large_1percent"

# ログ設定（頻度を上げる）
logging:
  log_every_n_steps: 5      # 10 → 5でより頻繁にログ